[tool.poetry]
name = "bl-matchmaker"
version = "0.1.0"
description = ""
authors = ["Forsee41 <forsee41@gmail.com>"]
readme = "README.md"
packages = [{include = "bl_matchmaker"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
